import 'package:flutter_test/flutter_test.dart';
import 'package:yourssh/models/firewall_status.dart';

void main() {
  group('FirewallStatus.fromShellOutput', () {
    test('parses active ufw with deny default and rules', () {
      const output = '''
Status: active
Logging: on (low)
Default: deny (incoming), allow (outgoing), disabled (routed)
New profiles: skip

     To                         Action      From
     --                         ------      ----
[ 1] 22/tcp                     ALLOW IN    Anywhere
[ 2] 80/tcp                     ALLOW IN    Anywhere
[ 3] 22/tcp (v6)                ALLOW IN    Anywhere (v6)
''';
      final s = FirewallStatus.fromShellOutput(output);
      expect(s.type, FirewallType.ufw);
      expect(s.enabled, isTrue);
      expect(s.defaultInboundPolicy, 'DENY');
      expect(s.rules.length, 3);
      expect(s.rules.first.action, 'ALLOW');
    });

    test('parses inactive ufw', () {
      final s = FirewallStatus.fromShellOutput('Status: inactive');
      expect(s.type, FirewallType.ufw);
      expect(s.enabled, isFalse);
      expect(s.rules, isEmpty);
    });

    test('parses iptables-save with DROP default', () {
      const output = '''
# Generated by iptables-save
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p tcp --dport 22 -j ACCEPT
-A INPUT -p tcp --dport 80 -j ACCEPT
COMMIT
''';
      final s = FirewallStatus.fromShellOutput(output);
      expect(s.type, FirewallType.iptables);
      expect(s.enabled, isTrue);
      expect(s.defaultInboundPolicy, 'DROP');
      final inputRules = s.rules.where((r) => r.chain == 'INPUT').toList();
      expect(inputRules.length, 3);
      expect(inputRules.last.action, 'ACCEPT');
    });

    test('parses nft ruleset', () {
      const output = '''
table inet filter {
    chain input {
        type filter hook input priority 0; policy drop;
        ct state established,related accept
        iif "lo" accept
        tcp dport 22 accept
    }
}
''';
      final s = FirewallStatus.fromShellOutput(output);
      expect(s.type, FirewallType.nftables);
      expect(s.enabled, isTrue);
      expect(s.defaultInboundPolicy, 'DROP');
      expect(s.rules.isNotEmpty, isTrue);
    });

    test('returns none for __NO_FIREWALL__ sentinel', () {
      final s = FirewallStatus.fromShellOutput('__NO_FIREWALL__\n');
      expect(s.type, FirewallType.none);
      expect(s.enabled, isFalse);
      expect(s.rules, isEmpty);
    });

    test('returns none for unrecognized output', () {
      final s = FirewallStatus.fromShellOutput('some random text');
      expect(s.type, FirewallType.none);
    });
  });
}
